FROM public.ecr.aws/lambda/python:3.13

COPY requirements/ ${LAMBDA_TASK_ROOT}/requirements/
RUN pip install --no-cache-dir -r requirements/prod.txt && \
    pip install --no-cache-dir -r requirements/dev.txt

COPY app.py ${LAMBDA_TASK_ROOT}
